### ISSUE TITLE
cannot start thread

### ISSUE THREAD

**Issue by duch3201** [duch3201/LightFile#14]
Traceback (most recent call last):
  File "Y:\LightFile\comrfile.py", line 201, in <module>
    threadforcompressing = mt._start_new_thread (compressed_data = zlib.compress(str, 9) )
TypeError: a bytes-like object is required, not 'type'

```
try:
  fileforcompressionthread = mt._start_new_thread(str = open(file_name, 'rb').read() ("thead-1") )  
  fileforcompressionthread.start()

except FileNotFoundError:
    logging.critical('This file does not exist!')
    print("This file does not exist!")
    print("error: 1")
    time.sleep(5)
    exit()
except:
    print("unable to start thread!" '\n' "Error: 5" )
    time.sleep(5)
   exit()
```

this is the part of the code that fails

**Comment by duch3201** [comment]
okay after adding ' ' to the **str** variable it goes on to the next thread start which is here

```
Traceback (most recent call last):
  File "Y:\LightFile\comrfile.py", line 201, in <module>
    threadforcompressing = mt._start_new_thread ('compressed_data' == zlib.compress(str, 9) )
TypeError: a bytes-like object is required, not 'type'
```

**Comment by duch3201** [comment]
```
compress(c) a file, or decompress(d) a file
: c
Selected to compress. Enter the input file
: Y:\bliss.jpg
Enter the path to the output folder
: Y:\
Traceback (most recent call last):
  File "Y:\LightFile\comrfile.py", line 181, in <module>
    fileforcompressionthread = mt._start_new_thread('str' == open(file_name, 'r').read() ("thread-1") )
  File "C:\Users\krzysztof\AppData\Local\Programs\Python\Python39\lib\encodings\cp1250.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 524: character maps to <undefined>
```
so i deleted the 
```
except:
    print("unable to start thread!" '\n' "Error: 5" )
    time.sleep(5)
    exit()
```
and it gave me the thing above

**Comment by duch3201** [comment]
![image](https://user-images.githubusercontent.com/56601374/106511243-43e52d00-64d0-11eb-9ad3-214348059a70.png)
okay so i added 
```
encoding="utf8", errors="ignore"
```
to line 182 and the thing above happen

**Comment by duch3201** [comment]
i gave up on multithreading
